# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Viriatto"
    reviewers:
      - "Viriatto"
    commit-message:
      include: "scope"
    groups:
      minor-patch-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      minor-patch-production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
