# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "Viriatto"
    commit-message:
      prefix: "[prod-dep] "
      prefix-development: "[dev-dep] "
      include: "scope"
    groups:
       minor-patch-development:
         dependency-type: "development"
         update-types:
           - "minor"
           - "patch"
       minor-patch-production:
         dependency-type: "production"
         update-types:
           - "minor"
           - "patch"
