# This workflow will check for Typescript errors once a PR is ready for review.
# For more information see: https://github.com/marketplace/actions/typescript-report

name: Typescript Error Checker

on:
  push:
    paths:
      - "src/*"

jobs:
  check-for-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npx tsc --noEmit --noErrorTruncation --pretty false
